#ifndef CPL_CPL_DIRECTIVES_H
#define CPL_CPL_DIRECTIVES_H

typedef enum {
    ARGS, BY, CALL, CHECK, DATA,
    DEBUG, DO, ECHO, ELSE, END,
    ERROR, EXECUTE, EXPAND, FAIL, GOTO,
    IF, IGNORE, ITEMS, LABEL, LIST,
    MESSAGE, NO_ECHO, NO_EXECUTE, NO_RETURN, NO_WATCH,
    ON, OTHERWISE, REPEAT, RESULT, RETURN, REVERT,
    ROUTINE, SELECT, SET_VAR, SEVERITY, SIGNAL,
    STOP, THEN, TO, TTY, TTY_CONTINUE,
    UNTIL, WARNING, WATCH, WHEN, WHILE
} CPL_DIR;

int is_cpl_directive(const char *dir);

#endif //CPL_CPL_DIRECTIVES_H
