#ifndef CPL_CPL_FUNCTIONS_H
#define CPL_CPL_FUNCTIONS_H

// struct for all functions.
typedef struct {
    const char *text;

} CPL_FUNC_UNK;

typedef enum {
    CABBREV, CAFTER, CATTRIB, CBEFORE, CCALC, CCLOSE,
    CCND_INFO, CDATE, CDIR, CENTRYNAME, CEXISTS,
    CEXPAND_SEARCH_RULES, CGET_VAR, CGVPATH, CHEX, CINDEX,
    CKLMD, CKLMF, CKLMT, CLENGTH, CMOD,
    CNULL, COCTAL, COPEN_FILE, CPATHNAME, CQUERY,
    CQUOTE, CREAD_FILE, CRESCAN, CRESPONSE, CRESUME,
    CSEARCH, CSUBST, CSUBSTR, CTO_HEX, CTO_OCTAL,
    CTRANSLATE, CTRIM, CUNQUOTE, CVERIFY, CWILD,
    CWRITE_FILE
} CPL_FUNC

#endif //CPL_CPL_FUNCTIONS_H
